### ISSUE TITLE
adding widget the right way

### ISSUE THREAD

**Issue by thunderjet12** [sumitpore/mvc-plugin-boilerplate-for-wordpress#25]
**Hi,**
Thanks for this awesome boilerplate

I have a question: I'm building a collection of **Elementor** widgets I what and which the best place or file to 
register the widgets and enqueue styles and js files.
here is my code
https://github.com/thunderjet12/sbird-admin

**Best regards ^_^**

**Comment by sumitpore** [comment]
Hi,

I would suggest creating a new folder 'widgets' inside 'controllers' folder and create widget classes inside that 'widgets' folder.

I think (not sure) you would have to load these widget classes on frontend as well as on frontend. If that is the case, you would have to use `ROUTE_TYPE::ANY` in `routes.php` for those widgets.

**Comment by thunderjet12** [comment]
> Hi,
> 
> I would suggest creating a new folder 'widgets' inside 'controllers' folder and create widget classes inside that 'widgets' folder.
> 
> I think (not sure) you would have to load these widget classes on frontend as well as on frontend. If that is the case, you would have to use `ROUTE_TYPE::ANY` in `routes.php` for those widgets.

Thanks a lot, ^_^
